version: '3.1'

services:
  web:
    container_name: php-laravel
    image: php:7.4-laravel
    build: 
      context: .
      dockerfile: php.dockerfile
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - ./projeto:/var/www/html/projeto
    ports:
      - 8083:80
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: projeto
      MYSQL_USER: uProjeto
      MYSQL_PASSWORD: sProjeto
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    networks: 
      - backend
networks:
  backend:
    driver: bridge
# shopt -s dotglob
# mv ../projeto/* projeto/
# chmod -R 777 . 
# php projeto/artisan key:generate