version: '3.1'

services:
  web:
    container_name: php-laravel
    image: php:7.4-laravel
    build: 
      context: .
      dockerfile: php.dockerfile
      args:
        NOME_PROJETO: teste #trocar aqui
    environment:
      NOME_PROJETO: teste #trocar aqui
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - ./projeto:/var/www/html/teste #trocar aqui
    ports:
      - 8083:80
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: projeto # definir aqui
      MYSQL_USER: uProjeto # definir aqui
      MYSQL_PASSWORD: sProjeto # definir aqui
      MYSQL_ROOT_PASSWORD: example # definir aqui
    ports:
      - "3306:3306"
    networks: 
      - backend
networks:
  backend:
    driver: bridge